//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 25/09/2016 12:40:24
namespace WaveFrogger
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/readme.txt </summary>
        public const string readme_txt = "Content/readme.txt";
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/FieldGrassMaterial.wmat </summary>
            public const string FieldGrassMaterial = "Content/Assets/FieldGrassMaterial.wmat";
            
            /// <summary> Path to Content/Assets/FieldTreeMaterial.wmat </summary>
            public const string FieldTreeMaterial = "Content/Assets/FieldTreeMaterial.wmat";
            
            /// <summary> Path to Content/Assets/FroggerMaterial.wmat </summary>
            public const string FroggerMaterial = "Content/Assets/FroggerMaterial.wmat";
            
            /// <summary> Path to Content/Assets/GrassMaterial.wmat </summary>
            public const string GrassMaterial = "Content/Assets/GrassMaterial.wmat";
            
            /// <summary> Path to Content/Assets/RoadCarMaterial.wmat </summary>
            public const string RoadCarMaterial = "Content/Assets/RoadCarMaterial.wmat";
            
            /// <summary> Path to Content/Assets/RoadCarMaterial2.wmat </summary>
            public const string RoadCarMaterial2 = "Content/Assets/RoadCarMaterial2.wmat";
            
            /// <summary> Path to Content/Assets/RoadMaterial.wmat </summary>
            public const string RoadMaterial = "Content/Assets/RoadMaterial.wmat";
            
            /// <summary> Path to Content/Assets/WaterMaterial.wmat </summary>
            public const string WaterMaterial = "Content/Assets/WaterMaterial.wmat";
            
            public sealed class Fonts
            {
                
                /// <summary> Path to Content/Assets/Fonts/8BITWONDER_24.TTF </summary>
                public const string _8BITWONDER_24_TTF = "Content/Assets/Fonts/8BITWONDER_24.TTF";
                
                /// <summary> Path to Content/Assets/Fonts/8BITWONDER_36.TTF </summary>
                public const string _8BITWONDER_36_TTF = "Content/Assets/Fonts/8BITWONDER_36.TTF";
                
                /// <summary> Path to Content/Assets/Fonts/8BITWONDER_60.TTF </summary>
                public const string _8BITWONDER_60_TTF = "Content/Assets/Fonts/8BITWONDER_60.TTF";
            }
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/Chicken.obj </summary>
                public const string Chicken_obj = "Content/Assets/Models/Chicken.obj";
                
                /// <summary> Path to Content/Assets/Models/coin.obj </summary>
                public const string coin_obj = "Content/Assets/Models/coin.obj";
                
                /// <summary> Path to Content/Assets/Models/lilypad.obj </summary>
                public const string lilypad_obj = "Content/Assets/Models/lilypad.obj";
                
                /// <summary> Path to Content/Assets/Models/log_1.obj </summary>
                public const string log_1_obj = "Content/Assets/Models/log_1.obj";
                
                /// <summary> Path to Content/Assets/Models/log_2.obj </summary>
                public const string log_2_obj = "Content/Assets/Models/log_2.obj";
                
                /// <summary> Path to Content/Assets/Models/Sedan.obj </summary>
                public const string Sedan_obj = "Content/Assets/Models/Sedan.obj";
                
                /// <summary> Path to Content/Assets/Models/strip_grass_1.obj </summary>
                public const string strip_grass_1_obj = "Content/Assets/Models/strip_grass_1.obj";
                
                /// <summary> Path to Content/Assets/Models/strip_road_1.obj </summary>
                public const string strip_road_1_obj = "Content/Assets/Models/strip_road_1.obj";
                
                /// <summary> Path to Content/Assets/Models/strip_train.obj </summary>
                public const string strip_train_obj = "Content/Assets/Models/strip_train.obj";
                
                /// <summary> Path to Content/Assets/Models/strip_water_1.obj </summary>
                public const string strip_water_1_obj = "Content/Assets/Models/strip_water_1.obj";
                
                /// <summary> Path to Content/Assets/Models/train_front.obj </summary>
                public const string train_front_obj = "Content/Assets/Models/train_front.obj";
                
                /// <summary> Path to Content/Assets/Models/train_light.obj </summary>
                public const string train_light_obj = "Content/Assets/Models/train_light.obj";
                
                /// <summary> Path to Content/Assets/Models/train_middle.obj </summary>
                public const string train_middle_obj = "Content/Assets/Models/train_middle.obj";
                
                /// <summary> Path to Content/Assets/Models/tree_1.obj </summary>
                public const string tree_1_obj = "Content/Assets/Models/tree_1.obj";
                
                /// <summary> Path to Content/Assets/Models/tree_2.obj </summary>
                public const string tree_2_obj = "Content/Assets/Models/tree_2.obj";
                
                /// <summary> Path to Content/Assets/Models/tree_3.obj </summary>
                public const string tree_3_obj = "Content/Assets/Models/tree_3.obj";
                
                /// <summary> Path to Content/Assets/Models/tree_4.obj </summary>
                public const string tree_4_obj = "Content/Assets/Models/tree_4.obj";
                
                /// <summary> Path to Content/Assets/Models/Truck.obj </summary>
                public const string Truck_obj = "Content/Assets/Models/Truck.obj";
                
                /// <summary> Path to Content/Assets/Models/Wagon.obj </summary>
                public const string Wagon_obj = "Content/Assets/Models/Wagon.obj";
            }
            
            public sealed class Music
            {
                
                /// <summary> Path to Content/Assets/Music/MrJellyRolls.mp3 </summary>
                public const string MrJellyRolls_mp3 = "Content/Assets/Music/MrJellyRolls.mp3";
            }
            
            public sealed class Sounds
            {
                
                /// <summary> Path to Content/Assets/Sounds/chicken1.wav </summary>
                public const string chicken1_wav = "Content/Assets/Sounds/chicken1.wav";
                
                /// <summary> Path to Content/Assets/Sounds/deadDrop1.wav </summary>
                public const string deadDrop1_wav = "Content/Assets/Sounds/deadDrop1.wav";
                
                /// <summary> Path to Content/Assets/Sounds/horn1.wav </summary>
                public const string horn1_wav = "Content/Assets/Sounds/horn1.wav";
                
                /// <summary> Path to Content/Assets/Sounds/horn2.wav </summary>
                public const string horn2_wav = "Content/Assets/Sounds/horn2.wav";
                
                /// <summary> Path to Content/Assets/Sounds/horn3.wav </summary>
                public const string horn3_wav = "Content/Assets/Sounds/horn3.wav";
                
                /// <summary> Path to Content/Assets/Sounds/horn4.wav </summary>
                public const string horn4_wav = "Content/Assets/Sounds/horn4.wav";
                
                /// <summary> Path to Content/Assets/Sounds/jump1.wav </summary>
                public const string jump1_wav = "Content/Assets/Sounds/jump1.wav";
                
                /// <summary> Path to Content/Assets/Sounds/jump2.wav </summary>
                public const string jump2_wav = "Content/Assets/Sounds/jump2.wav";
                
                /// <summary> Path to Content/Assets/Sounds/jump3.wav </summary>
                public const string jump3_wav = "Content/Assets/Sounds/jump3.wav";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/Chicken-tex-tex.png </summary>
                public const string Chicken_tex_tex_png = "Content/Assets/Textures/Chicken-tex-tex.png";
                
                /// <summary> Path to Content/Assets/Textures/coin-tex.tex.png </summary>
                public const string coin_tex_tex_png = "Content/Assets/Textures/coin-tex.tex.png";
                
                /// <summary> Path to Content/Assets/Textures/lilypad-tex.tex.png </summary>
                public const string lilypad_tex_tex_png = "Content/Assets/Textures/lilypad-tex.tex.png";
                
                /// <summary> Path to Content/Assets/Textures/log_1-tex.tex.png </summary>
                public const string log_1_tex_tex_png = "Content/Assets/Textures/log_1-tex.tex.png";
                
                /// <summary> Path to Content/Assets/Textures/log_2-tex.tex.png </summary>
                public const string log_2_tex_tex_png = "Content/Assets/Textures/log_2-tex.tex.png";
                
                /// <summary> Path to Content/Assets/Textures/Sedan-tex.tex.png </summary>
                public const string Sedan_tex_tex_png = "Content/Assets/Textures/Sedan-tex.tex.png";
                
                /// <summary> Path to Content/Assets/Textures/strip_grass_1-tex.tex.png </summary>
                public const string strip_grass_1_tex_tex_png = "Content/Assets/Textures/strip_grass_1-tex.tex.png";
                
                /// <summary> Path to Content/Assets/Textures/strip_road_1-tex.tex.png </summary>
                public const string strip_road_1_tex_tex_png = "Content/Assets/Textures/strip_road_1-tex.tex.png";
                
                /// <summary> Path to Content/Assets/Textures/strip_road_2-tex.tex.png </summary>
                public const string strip_road_2_tex_tex_png = "Content/Assets/Textures/strip_road_2-tex.tex.png";
                
                /// <summary> Path to Content/Assets/Textures/strip_train-tex.tex.png </summary>
                public const string strip_train_tex_tex_png = "Content/Assets/Textures/strip_train-tex.tex.png";
                
                /// <summary> Path to Content/Assets/Textures/strip_water_1-tex.tex.png </summary>
                public const string strip_water_1_tex_tex_png = "Content/Assets/Textures/strip_water_1-tex.tex.png";
                
                /// <summary> Path to Content/Assets/Textures/train_front-tex.tex.png </summary>
                public const string train_front_tex_tex_png = "Content/Assets/Textures/train_front-tex.tex.png";
                
                /// <summary> Path to Content/Assets/Textures/train_light_off-tex.tex.png </summary>
                public const string train_light_off_tex_tex_png = "Content/Assets/Textures/train_light_off-tex.tex.png";
                
                /// <summary> Path to Content/Assets/Textures/train_middle-tex.tex.png </summary>
                public const string train_middle_tex_tex_png = "Content/Assets/Textures/train_middle-tex.tex.png";
                
                /// <summary> Path to Content/Assets/Textures/tree_1-tex.tex.png </summary>
                public const string tree_1_tex_tex_png = "Content/Assets/Textures/tree_1-tex.tex.png";
                
                /// <summary> Path to Content/Assets/Textures/tree_2-tex.tex.png </summary>
                public const string tree_2_tex_tex_png = "Content/Assets/Textures/tree_2-tex.tex.png";
                
                /// <summary> Path to Content/Assets/Textures/tree_3-tex.tex.png </summary>
                public const string tree_3_tex_tex_png = "Content/Assets/Textures/tree_3-tex.tex.png";
                
                /// <summary> Path to Content/Assets/Textures/tree_4-tex.tex.png </summary>
                public const string tree_4_tex_tex_png = "Content/Assets/Textures/tree_4-tex.tex.png";
                
                /// <summary> Path to Content/Assets/Textures/Truck-tex.tex.png </summary>
                public const string Truck_tex_tex_png = "Content/Assets/Textures/Truck-tex.tex.png";
                
                /// <summary> Path to Content/Assets/Textures/Wagon-tex.tex.png </summary>
                public const string Wagon_tex_tex_png = "Content/Assets/Textures/Wagon-tex.tex.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/ChickenMat.wmat </summary>
                public const string ChickenMat = "Content/Assets/Materials/ChickenMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/coinMat.wmat </summary>
                public const string coinMat = "Content/Assets/Materials/coinMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/grassMat.wmat </summary>
                public const string grassMat = "Content/Assets/Materials/grassMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/greenCarMat.wmat </summary>
                public const string greenCarMat = "Content/Assets/Materials/greenCarMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/lilyMat.wmat </summary>
                public const string lilyMat = "Content/Assets/Materials/lilyMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/log2Mat.wmat </summary>
                public const string log2Mat = "Content/Assets/Materials/log2Mat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/logMat.wmat </summary>
                public const string logMat = "Content/Assets/Materials/logMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/MyMat.wmat </summary>
                public const string MyMat = "Content/Assets/Materials/MyMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/orangeCarMat.wmat </summary>
                public const string orangeCarMat = "Content/Assets/Materials/orangeCarMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/RedTruckMat.wmat </summary>
                public const string RedTruckMat = "Content/Assets/Materials/RedTruckMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/road2Mat.wmat </summary>
                public const string road2Mat = "Content/Assets/Materials/road2Mat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/roadMat.wmat </summary>
                public const string roadMat = "Content/Assets/Materials/roadMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/TrainFrontMat.wmat </summary>
                public const string TrainFrontMat = "Content/Assets/Materials/TrainFrontMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/TrainLightMat.wmat </summary>
                public const string TrainLightMat = "Content/Assets/Materials/TrainLightMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/trainMat.wmat </summary>
                public const string trainMat = "Content/Assets/Materials/trainMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/TrainMiddleMat.wmat </summary>
                public const string TrainMiddleMat = "Content/Assets/Materials/TrainMiddleMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Tree1Mat.wmat </summary>
                public const string Tree1Mat = "Content/Assets/Materials/Tree1Mat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Tree2Mat.wmat </summary>
                public const string Tree2Mat = "Content/Assets/Materials/Tree2Mat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Tree3Mat.wmat </summary>
                public const string Tree3Mat = "Content/Assets/Materials/Tree3Mat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/Tree4Mat.wmat </summary>
                public const string Tree4Mat = "Content/Assets/Materials/Tree4Mat.wmat";
            }
        }
        
        public sealed class Prefabs
        {
            
            /// <summary> Path to Content/Prefabs/car01.wpref </summary>
            public const string car01 = "Content/Prefabs/car01.wpref";
            
            /// <summary> Path to Content/Prefabs/car02.wpref </summary>
            public const string car02 = "Content/Prefabs/car02.wpref";
            
            /// <summary> Path to Content/Prefabs/car03.wpref </summary>
            public const string car03 = "Content/Prefabs/car03.wpref";
            
            /// <summary> Path to Content/Prefabs/defaultRow.wpref </summary>
            public const string defaultRow = "Content/Prefabs/defaultRow.wpref";
            
            /// <summary> Path to Content/Prefabs/fieldRow.wpref </summary>
            public const string fieldRow = "Content/Prefabs/fieldRow.wpref";
            
            /// <summary> Path to Content/Prefabs/roadRow.wpref </summary>
            public const string roadRow = "Content/Prefabs/roadRow.wpref";
            
            /// <summary> Path to Content/Prefabs/Tree01.wpref </summary>
            public const string Tree01 = "Content/Prefabs/Tree01.wpref";
            
            /// <summary> Path to Content/Prefabs/Tree02.wpref </summary>
            public const string Tree02 = "Content/Prefabs/Tree02.wpref";
            
            /// <summary> Path to Content/Prefabs/Tree03.wpref </summary>
            public const string Tree03 = "Content/Prefabs/Tree03.wpref";
            
            /// <summary> Path to Content/Prefabs/Tree04.wpref </summary>
            public const string Tree04 = "Content/Prefabs/Tree04.wpref";
            
            /// <summary> Path to Content/Prefabs/treelimits.wpref </summary>
            public const string treelimits = "Content/Prefabs/treelimits.wpref";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/GameScene.wscene </summary>
            public const string GameScene = "Content/Scenes/GameScene.wscene";
            
            /// <summary> Path to Content/Scenes/InitialScene.wscene </summary>
            public const string InitialScene = "Content/Scenes/InitialScene.wscene";
        }
    }
}
