//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 17/11/2016 20:56:33
namespace HoloPlanets
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/MyMaterial.wmat </summary>
                public const string MyMaterial = "Content/Assets/Materials/MyMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/sunMaterial.wmat </summary>
                public const string sunMaterial = "Content/Assets/Materials/sunMaterial.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
