//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 30/09/2016 17:34:28
namespace Orbit
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/Background.fbx </summary>
                public const string Background_fbx = "Content/Assets/Models/Background.fbx";
                
                /// <summary> Path to Content/Assets/Models/Earth.FBX </summary>
                public const string Earth_FBX = "Content/Assets/Models/Earth.FBX";
                
                /// <summary> Path to Content/Assets/Models/Jupiter.FBX </summary>
                public const string Jupiter_FBX = "Content/Assets/Models/Jupiter.FBX";
                
                /// <summary> Path to Content/Assets/Models/Mars.FBX </summary>
                public const string Mars_FBX = "Content/Assets/Models/Mars.FBX";
                
                /// <summary> Path to Content/Assets/Models/Mercury.FBX </summary>
                public const string Mercury_FBX = "Content/Assets/Models/Mercury.FBX";
                
                /// <summary> Path to Content/Assets/Models/Moon.FBX </summary>
                public const string Moon_FBX = "Content/Assets/Models/Moon.FBX";
                
                /// <summary> Path to Content/Assets/Models/Neptune.FBX </summary>
                public const string Neptune_FBX = "Content/Assets/Models/Neptune.FBX";
                
                /// <summary> Path to Content/Assets/Models/Orbits.FBX </summary>
                public const string Orbits_FBX = "Content/Assets/Models/Orbits.FBX";
                
                /// <summary> Path to Content/Assets/Models/Pluton.FBX </summary>
                public const string Pluton_FBX = "Content/Assets/Models/Pluton.FBX";
                
                /// <summary> Path to Content/Assets/Models/Saturn.FBX </summary>
                public const string Saturn_FBX = "Content/Assets/Models/Saturn.FBX";
                
                /// <summary> Path to Content/Assets/Models/Sun.FBX </summary>
                public const string Sun_FBX = "Content/Assets/Models/Sun.FBX";
                
                /// <summary> Path to Content/Assets/Models/Uranus.FBX </summary>
                public const string Uranus_FBX = "Content/Assets/Models/Uranus.FBX";
                
                /// <summary> Path to Content/Assets/Models/Venus.FBX </summary>
                public const string Venus_FBX = "Content/Assets/Models/Venus.FBX";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/Earth_512.png </summary>
                public const string Earth_512_png = "Content/Assets/Textures/Earth_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Jupiter_512.png </summary>
                public const string Jupiter_512_png = "Content/Assets/Textures/Jupiter_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Mars_512.png </summary>
                public const string Mars_512_png = "Content/Assets/Textures/Mars_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Mercury_512.png </summary>
                public const string Mercury_512_png = "Content/Assets/Textures/Mercury_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Moon_512.png </summary>
                public const string Moon_512_png = "Content/Assets/Textures/Moon_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Neptune_512.png </summary>
                public const string Neptune_512_png = "Content/Assets/Textures/Neptune_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Pluto_512.png </summary>
                public const string Pluto_512_png = "Content/Assets/Textures/Pluto_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Saturn_512.png </summary>
                public const string Saturn_512_png = "Content/Assets/Textures/Saturn_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Sun_512.png </summary>
                public const string Sun_512_png = "Content/Assets/Textures/Sun_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Uranus_512.png </summary>
                public const string Uranus_512_png = "Content/Assets/Textures/Uranus_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Venus_512.png </summary>
                public const string Venus_512_png = "Content/Assets/Textures/Venus_512.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/backgroundMat.wmat </summary>
                public const string backgroundMat = "Content/Assets/Materials/backgroundMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/earthMat.wmat </summary>
                public const string earthMat = "Content/Assets/Materials/earthMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/jupiterMat.wmat </summary>
                public const string jupiterMat = "Content/Assets/Materials/jupiterMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/marsMat.wmat </summary>
                public const string marsMat = "Content/Assets/Materials/marsMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/mercuryMat.wmat </summary>
                public const string mercuryMat = "Content/Assets/Materials/mercuryMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/moonMat.wmat </summary>
                public const string moonMat = "Content/Assets/Materials/moonMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/neptuneMat.wmat </summary>
                public const string neptuneMat = "Content/Assets/Materials/neptuneMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/orbitMat.wmat </summary>
                public const string orbitMat = "Content/Assets/Materials/orbitMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/plutonMat.wmat </summary>
                public const string plutonMat = "Content/Assets/Materials/plutonMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/saturnMat.wmat </summary>
                public const string saturnMat = "Content/Assets/Materials/saturnMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/sunMat.wmat </summary>
                public const string sunMat = "Content/Assets/Materials/sunMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/uranusMat.wmat </summary>
                public const string uranusMat = "Content/Assets/Materials/uranusMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/venusMat.wmat </summary>
                public const string venusMat = "Content/Assets/Materials/venusMat.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
