//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17626
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace HelloSilverlight.Resources
{
   using System;

   /// <summary>
   ///   Clase de recurso fuertemente tipado para buscar cadenas traducidas, etc.
   /// </summary>
   // StronglyTypedResourceBuilder generó automáticamente esta clase
   // a través de una herramienta como ResGen o Visual Studio.
   // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
   // con la opción /str o recompila tu proyecto de Visual Studio.
   public class AppResources
   {

      internal AppResources()
      {
      }

      /// <summary>
      ///   Busca una cadena traducida similar a LeftToRight.
      /// </summary>
      public static string ResourceFlowDirection
      {
         get
         {
            return GetString("ResourceFlowDirection");
         }
      }

      /// <summary>
      ///   Busca una cadena traducida similar a us-EN.
      /// </summary>
      public static string ResourceLanguage
      {
         get
         {
            return GetString("ResourceLanguage");
         }
      }

      /// <summary>
      ///   Busca una cadena traducida similar a MI APLICACIÓN.
      /// </summary>
      public static string ApplicationTitle
      {
         get
         {
            return GetString("ApplicationTitle");
         }
      }

      /// <summary>
      ///   Busca una cadena traducida similar a botón
      /// </summary>
      public static string AppBarButtonText
      {
         get
         {
            return GetString("AppBarButtonText");
         }
      }

      /// <summary>
      ///   Busca una cadena traducida similar a elemento de menú.
      /// </summary>
      public static string AppBarMenuItemText
      {
         get
         {
            return GetString("AppBarMenuItemText");
         }
      }

      private static string GetString(string key)
      {
         Windows.ApplicationModel.Resources.ResourceLoader loader = Windows.ApplicationModel.Resources.ResourceLoader.GetForCurrentView("AppResources");
         return loader.GetString(key);
      }

   }

}