//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 29/05/2018 17:24:25
namespace XamarinForms3DCarSample
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/XamarinForms3DCarSample.wgame </summary>
        public const string GameInfo = "Content/XamarinForms3DCarSample.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/datsun240k.fbx </summary>
                public const string datsun240k_fbx = "Content/Assets/Models/datsun240k.fbx";
                
                public sealed class Materials
                {
                    
                    /// <summary> Path to Content/Assets/Models/Materials/Skybox.cubemap </summary>
                    public const string Skybox_cubemap = "Content/Assets/Models/Materials/Skybox.cubemap";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/alloy.wmat </summary>
                    public const string alloy = "Content/Assets/Models/Materials/alloy.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/black_matte.wmat </summary>
                    public const string black_matte = "Content/Assets/Models/Materials/black_matte.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/black_paint.wmat </summary>
                    public const string black_paint = "Content/Assets/Models/Materials/black_paint.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/chrome.wmat </summary>
                    public const string chrome = "Content/Assets/Models/Materials/chrome.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/coat.wmat </summary>
                    public const string coat = "Content/Assets/Models/Materials/coat.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/DefaultMaterial.wmat </summary>
                    public const string DefaultMaterial = "Content/Assets/Models/Materials/DefaultMaterial.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/glass.wmat </summary>
                    public const string glass = "Content/Assets/Models/Materials/glass.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/headlights.wmat </summary>
                    public const string headlights = "Content/Assets/Models/Materials/headlights.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/license.wmat </summary>
                    public const string license = "Content/Assets/Models/Materials/license.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/orange_glass.wmat </summary>
                    public const string orange_glass = "Content/Assets/Models/Materials/orange_glass.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/paint.wmat </summary>
                    public const string paint = "Content/Assets/Models/Materials/paint.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/red_glass.wmat </summary>
                    public const string red_glass = "Content/Assets/Models/Materials/red_glass.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/stickers.wmat </summary>
                    public const string stickers = "Content/Assets/Models/Materials/stickers.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/tire.wmat </summary>
                    public const string tire = "Content/Assets/Models/Materials/tire.wmat";
                }
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/black.png </summary>
                public const string black_png = "Content/Assets/Textures/black.png";
                
                /// <summary> Path to Content/Assets/Textures/c4d13e1ef5c20e49d7206aefff123f19--no-signa.jpg </summary>
                public const string c4d13e1ef5c20e49d7206aefff123f19_no_signa_jpg = "Content/Assets/Textures/c4d13e1ef5c20e49d7206aefff123f19--no-signa.jpg";
                
                /// <summary> Path to Content/Assets/Textures/headlight_normal.jpg </summary>
                public const string headlight_normal_jpg = "Content/Assets/Textures/headlight_normal.jpg";
                
                /// <summary> Path to Content/Assets/Textures/plate.png </summary>
                public const string plate_png = "Content/Assets/Textures/plate.png";
                
                /// <summary> Path to Content/Assets/Textures/shadow.png </summary>
                public const string shadow_png = "Content/Assets/Textures/shadow.png";
                
                /// <summary> Path to Content/Assets/Textures/stickers.png </summary>
                public const string stickers_png = "Content/Assets/Textures/stickers.png";
                
                /// <summary> Path to Content/Assets/Textures/tire.png </summary>
                public const string tire_png = "Content/Assets/Textures/tire.png";
                
                /// <summary> Path to Content/Assets/Textures/tire3.png </summary>
                public const string tire3_png = "Content/Assets/Textures/tire3.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/floorMaterial.wmat </summary>
                public const string floorMaterial = "Content/Assets/Materials/floorMaterial.wmat";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/Loading.wscene </summary>
            public const string Loading = "Content/Scenes/Loading.wscene";
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
