//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 30/09/2017 16:44:31
namespace HoloPlanets
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/HoloPlanets.wgame </summary>
        public const string GameInfo = "Content/HoloPlanets.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/cursorPlane.fbx </summary>
                public const string cursorPlane_fbx = "Content/Assets/Models/cursorPlane.fbx";
                
                /// <summary> Path to Content/Assets/Models/Earth.fbx </summary>
                public const string Earth_fbx = "Content/Assets/Models/Earth.fbx";
                
                /// <summary> Path to Content/Assets/Models/Sun.fbx </summary>
                public const string Sun_fbx = "Content/Assets/Models/Sun.fbx";
                
                public sealed class Materials
                {
                    
                    /// <summary> Path to Content/Assets/Models/Materials/Material #25.wmat </summary>
                    public const string Material_25 = "Content/Assets/Models/Materials/Material #25.wmat";
                }
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/donut.png </summary>
                public const string donut_png = "Content/Assets/Textures/donut.png";
                
                /// <summary> Path to Content/Assets/Textures/dot.png </summary>
                public const string dot_png = "Content/Assets/Textures/dot.png";
                
                /// <summary> Path to Content/Assets/Textures/Earth_512.png </summary>
                public const string Earth_512_png = "Content/Assets/Textures/Earth_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Sun_512.png </summary>
                public const string Sun_512_png = "Content/Assets/Textures/Sun_512.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/donutMaterial.wmat </summary>
                public const string donutMaterial = "Content/Assets/Materials/donutMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/dotMaterial.wmat </summary>
                public const string dotMaterial = "Content/Assets/Materials/dotMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/earthMaterial.wmat </summary>
                public const string earthMaterial = "Content/Assets/Materials/earthMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/paneMaterial.wmat </summary>
                public const string paneMaterial = "Content/Assets/Materials/paneMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/sunMaterial.wmat </summary>
                public const string sunMaterial = "Content/Assets/Materials/sunMaterial.wmat";
            }
            
            public sealed class Prefabs
            {
                
                /// <summary> Path to Content/Assets/Prefabs/AirTap.wpref </summary>
                public const string AirTap = "Content/Assets/Prefabs/AirTap.wpref";
                
                /// <summary> Path to Content/Assets/Prefabs/Ready.wpref </summary>
                public const string Ready = "Content/Assets/Prefabs/Ready.wpref";
                
                /// <summary> Path to Content/Assets/Prefabs/Undetected.wpref </summary>
                public const string Undetected = "Content/Assets/Prefabs/Undetected.wpref";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
