//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 29/09/2017 18:05:36
namespace HoloPlanets
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/HoloPlanets.wgame </summary>
        public const string GameInfo = "Content/HoloPlanets.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/cursorPlane.FBX </summary>
                public const string cursorPlane_FBX = "Content/Assets/Models/cursorPlane.FBX";
                
                /// <summary> Path to Content/Assets/Models/Earth.FBX </summary>
                public const string Earth_FBX = "Content/Assets/Models/Earth.FBX";
                
                /// <summary> Path to Content/Assets/Models/Jupiter.FBX </summary>
                public const string Jupiter_FBX = "Content/Assets/Models/Jupiter.FBX";
                
                /// <summary> Path to Content/Assets/Models/Mars.FBX </summary>
                public const string Mars_FBX = "Content/Assets/Models/Mars.FBX";
                
                /// <summary> Path to Content/Assets/Models/Mercury.FBX </summary>
                public const string Mercury_FBX = "Content/Assets/Models/Mercury.FBX";
                
                /// <summary> Path to Content/Assets/Models/Moon.FBX </summary>
                public const string Moon_FBX = "Content/Assets/Models/Moon.FBX";
                
                /// <summary> Path to Content/Assets/Models/Neptune.FBX </summary>
                public const string Neptune_FBX = "Content/Assets/Models/Neptune.FBX";
                
                /// <summary> Path to Content/Assets/Models/Orbits.FBX </summary>
                public const string Orbits_FBX = "Content/Assets/Models/Orbits.FBX";
                
                /// <summary> Path to Content/Assets/Models/Pluton.FBX </summary>
                public const string Pluton_FBX = "Content/Assets/Models/Pluton.FBX";
                
                /// <summary> Path to Content/Assets/Models/Saturn.FBX </summary>
                public const string Saturn_FBX = "Content/Assets/Models/Saturn.FBX";
                
                /// <summary> Path to Content/Assets/Models/Sun.FBX </summary>
                public const string Sun_FBX = "Content/Assets/Models/Sun.FBX";
                
                /// <summary> Path to Content/Assets/Models/Uranus.FBX </summary>
                public const string Uranus_FBX = "Content/Assets/Models/Uranus.FBX";
                
                /// <summary> Path to Content/Assets/Models/Venus.FBX </summary>
                public const string Venus_FBX = "Content/Assets/Models/Venus.FBX";
                
                public sealed class Materials
                {
                    
                    /// <summary> Path to Content/Assets/Models/Materials/02 - Default.wmat </summary>
                    public const string _02_Default = "Content/Assets/Models/Materials/02 - Default.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/04 - Default.wmat </summary>
                    public const string _04_Default = "Content/Assets/Models/Materials/04 - Default.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/05 - Default.wmat </summary>
                    public const string _05_Default = "Content/Assets/Models/Materials/05 - Default.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/07 - Default.wmat </summary>
                    public const string _07_Default = "Content/Assets/Models/Materials/07 - Default.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/08 - Default.wmat </summary>
                    public const string _08_Default = "Content/Assets/Models/Materials/08 - Default.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/09 - Default.wmat </summary>
                    public const string _09_Default = "Content/Assets/Models/Materials/09 - Default.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/10 - Default.wmat </summary>
                    public const string _10_Default = "Content/Assets/Models/Materials/10 - Default.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/11 - Default.wmat </summary>
                    public const string _11_Default = "Content/Assets/Models/Materials/11 - Default.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/13 - Default.wmat </summary>
                    public const string _13_Default = "Content/Assets/Models/Materials/13 - Default.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/14 - Default.wmat </summary>
                    public const string _14_Default = "Content/Assets/Models/Materials/14 - Default.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/earth.wmat </summary>
                    public const string earth = "Content/Assets/Models/Materials/earth.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/Material #25.wmat </summary>
                    public const string Material_25 = "Content/Assets/Models/Materials/Material #25.wmat";
                    
                    /// <summary> Path to Content/Assets/Models/Materials/venus.wmat </summary>
                    public const string venus = "Content/Assets/Models/Materials/venus.wmat";
                }
            }
            
            public sealed class Sounds
            {
                
                /// <summary> Path to Content/Assets/Sounds/background.wav </summary>
                public const string background_wav = "Content/Assets/Sounds/background.wav";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/donut.png </summary>
                public const string donut_png = "Content/Assets/Textures/donut.png";
                
                /// <summary> Path to Content/Assets/Textures/dot.png </summary>
                public const string dot_png = "Content/Assets/Textures/dot.png";
                
                /// <summary> Path to Content/Assets/Textures/Earth_512.png </summary>
                public const string Earth_512_png = "Content/Assets/Textures/Earth_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Jupiter_512.png </summary>
                public const string Jupiter_512_png = "Content/Assets/Textures/Jupiter_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Mars_512.png </summary>
                public const string Mars_512_png = "Content/Assets/Textures/Mars_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Mercury_512.png </summary>
                public const string Mercury_512_png = "Content/Assets/Textures/Mercury_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Moon_512.png </summary>
                public const string Moon_512_png = "Content/Assets/Textures/Moon_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Neptune_512.png </summary>
                public const string Neptune_512_png = "Content/Assets/Textures/Neptune_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Pluto_512.png </summary>
                public const string Pluto_512_png = "Content/Assets/Textures/Pluto_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Saturn_512.png </summary>
                public const string Saturn_512_png = "Content/Assets/Textures/Saturn_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Sun_512.png </summary>
                public const string Sun_512_png = "Content/Assets/Textures/Sun_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Uranus_512.png </summary>
                public const string Uranus_512_png = "Content/Assets/Textures/Uranus_512.png";
                
                /// <summary> Path to Content/Assets/Textures/Venus_512.png </summary>
                public const string Venus_512_png = "Content/Assets/Textures/Venus_512.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/donutMat.wmat </summary>
                public const string donutMat = "Content/Assets/Materials/donutMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/dotMat.wmat </summary>
                public const string dotMat = "Content/Assets/Materials/dotMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/earthMat.wmat </summary>
                public const string earthMat = "Content/Assets/Materials/earthMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/jupiterMat.wmat </summary>
                public const string jupiterMat = "Content/Assets/Materials/jupiterMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/marsMat.wmat </summary>
                public const string marsMat = "Content/Assets/Materials/marsMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/mercuryMat.wmat </summary>
                public const string mercuryMat = "Content/Assets/Materials/mercuryMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/moonMat.wmat </summary>
                public const string moonMat = "Content/Assets/Materials/moonMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/neptuneMat.wmat </summary>
                public const string neptuneMat = "Content/Assets/Materials/neptuneMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/orbitMat.wmat </summary>
                public const string orbitMat = "Content/Assets/Materials/orbitMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/paneMat.wmat </summary>
                public const string paneMat = "Content/Assets/Materials/paneMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/plutonMat.wmat </summary>
                public const string plutonMat = "Content/Assets/Materials/plutonMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/saturnMat.wmat </summary>
                public const string saturnMat = "Content/Assets/Materials/saturnMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/sunMat.wmat </summary>
                public const string sunMat = "Content/Assets/Materials/sunMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/uranusMat.wmat </summary>
                public const string uranusMat = "Content/Assets/Materials/uranusMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/venusMat.wmat </summary>
                public const string venusMat = "Content/Assets/Materials/venusMat.wmat";
            }
            
            public sealed class Prefabs
            {
                
                /// <summary> Path to Content/Assets/Prefabs/AirTap.wpref </summary>
                public const string AirTap = "Content/Assets/Prefabs/AirTap.wpref";
                
                /// <summary> Path to Content/Assets/Prefabs/Ready.wpref </summary>
                public const string Ready = "Content/Assets/Prefabs/Ready.wpref";
                
                /// <summary> Path to Content/Assets/Prefabs/Undetected.wpref </summary>
                public const string Undetected = "Content/Assets/Prefabs/Undetected.wpref";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
