//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 25/09/2017 20:53:23
namespace HoloPlanets
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/HoloPlanets.wgame </summary>
        public const string GameInfo = "Content/HoloPlanets.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/MyMaterial.wmat </summary>
                public const string MyMaterial = "Content/Assets/Materials/MyMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/sunMaterial.wmat </summary>
                public const string sunMaterial = "Content/Assets/Materials/sunMaterial.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
